version: '3'

######## app下api+rpc ,  启动本项目之前，要先启动本项目依赖的环境docker-compose-env.yml #######

services:

  #前端网关nginx-gateay (只代理trytry，admin-api不在这里做代理)
  nginx-gateway:
    image: nginx:1.21.5
    container_name: nginx-gateway
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:8081"
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    networks:
      - backend


  #前端api + 业务rpc
  cloud_disk:
    image: d254593eef5a     # if you "macOs intel" or "linux amd"
    container_name: cloud_disk
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    working_dir: /go/cloud_disk
    volumes:
      - .:/go/cloud_disk
    privileged: true
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

